seed: 7113064165
batch_size: 8
num_workers: 16
epochs: 1500
dataset_file: SHHA
data_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\train_data'
val_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\train_data\images'
test_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\test_data'
mode: 'points'                 # 'density' | 'points' | 'class'
crop_size:  [256, 256]
crop_type: 'center'
gray: False
device: cuda
out_dir: 'D:\output\PointRCNN_refine_ConfidenceHead_with_token_ConfidenceHeadWITHOUT6'
#---------------------------MODEL-----------------------------------------------------
in_ch: 3  # 1=灰階, 3=RGB
fpn_c: 128
cond_c: 64
t_dim: 256
with_score: True
lr: 1e-4
lr_backbone: 1e-5
diffusion_T: 1000
K: 5
signal_scale: 2.0
lambda_exist: 300.
lambda_x0: 0.1
lambda_cnt: 0.01
lambda_bg: 10
log_every:  50
max_norm:  10.0
#---------------------------realization-----------------------------------------------------
ckpt_path: 'D:\output\PointRCNN_refine_ConfidenceHead_with_token_ConfidenceHeadWITHOUT6\last_epoch0174.pth'
save_dir: 'C:\pycharm\pointdiff_new\vis_results\all_patch\Dynamic_adjustment_neg_w_0174'
hard_thresh: 0.01
metric: 'hard'
pick_worst: False
num_realizations: 1
ddim_steps: 50
eps_clip: 1e-3
inner_margin_ratio: 0.001
nms_r_ratio: 0.001
top_k_vis: 10
