seed: 7113064165
batch_size: 16
num_workers: 16
epochs: 1500
dataset_file: SHHA
data_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\train_data'
val_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\train_data\images'
test_root: 'C:\pycharm\dataset\ShanghaiTech_Crowd_Counting_Dataset\part_A_final\test_data'
mode: 'points'                 # 'density' | 'points' | 'class'
crop_size:  [256, 256]
crop_type: 'center'
gray: False
device: cuda
out_dir: 'D:\output\P2P_LCOV_rand_aux_from_mild0007'
#---------------------------MODEL-----------------------------------------------------
in_ch: 3  # 1=灰階, 3=RGB
fpn_c: 128
cond_c: 64
t_dim: 256
with_score: True
lr: 1e-5
lr_backbone: 1e-6
diffusion_T: 1000
K: 5
signal_scale: 2.0
lambda_exist: 120.
lambda_x0: 10.0
lambda_eps: 0.1
lambda_cnt: 0.02
lambda_bg: 0
lambda_cov: 2
lambda_cov_hinge: 5
lambda_rand_cover: 0.5
rand_cover_t_min: 700
rand_cover_t_max: 999
rand_cover_radius: 6.0
lambda_dup: 0
cov_topk: 5
cov_sigma: 6.0
cov_radius: 6.0
region_radius: 6.0
region_topk: 5
log_every:  50
max_norm:  10.0
#---------------------------realization-----------------------------------------------------
ckpt_path: 'D:\output\P2P_LCOV_non_gt_mild\last_epoch0007.pth'
save_dir: 'C:\pycharm\pointdiff_new\vis_results\all_patch\P2P_LCOV_rand_aux_from_mild0007'
hard_thresh: 0.2
nms_radius: 5.0
metric: 'hard'
pick_worst: False
num_realizations: 3
ddim_steps: 50
eps_clip: 1e-3
inner_margin_ratio: 0.001
nms_r_ratio: 0.001
top_k_vis: 10
ddim_eta: 0
diag_prob_hi: 0.45
diag_prob_lo: 0.15
test_gate_mode: prob_only
